FROM node:14

# Instala dependências do sistema (phantomjs)
RUN apt-get update && apt-get install -y libfontconfig

# Instala dependências necessárias ao Chromium usado pelo Puppeteer
RUN apt-get update && apt-get install -y \
    wget \
    ca-certificates \
    fonts-liberation \
    libappindicator3-1 \
    libasound2 \
    libatk-bridge2.0-0 \
    libatk1.0-0 \
    libcups2 \
    libdbus-1-3 \
    libdrm2 \
    libgbm1 \
    libnspr4 \
    libnss3 \
    libx11-xcb1 \
    libxcomposite1 \
    libxdamage1 \
    libxrandr2 \
    xdg-utils \
    libu2f-udev \
    libxss1 \
    --no-install-recommends && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

# Cria diretório de trabalho
WORKDIR /app

# Copia os arquivos do projeto
COPY package*.json ./
COPY server.js boleto.html ./

# Instala dependências Node
RUN npm install

# Expõe a porta da API
EXPOSE 3000

# Comando para rodar o app
CMD ["npm", "start"]
